### ISSUE TITLE
Save the current time when the consent was given or denied

### ISSUE THREAD

**Issue by kaszarobert** [jfeltkamp/cookiesjsr#12]
Is it possible to save not just the selected categories but the time when was the user's decision made?

**Comment by JPustkuchen** [comment]
Not a bad idea, what's the use of it? Does https://www.drupal.org/project/klaro solve this already @kaszarobert otherwise maybe also create an issue over there?

**Comment by JPustkuchen** [comment]
I'd vote to postpone or close this, if we have no real world use-case.

**Comment by jfeltkamp** [comment]
The cookie saves already the time, when it was set, updated or used. But I can't imagine a good use-case.
