### ISSUE TITLE
Re-animation of knocked out services example script doesn't work

### ISSUE THREAD

**Issue by kaszarobert** [jfeltkamp/cookiesjsr#13]
The activate part only works for me with this code:

```
         jQuery('script[data-sid="extservice"]').each(function() {
            var replacement = jQuery(this).clone().removeAttr('type');
            jQuery(this).replaceWith(replacement.html());
         });
```

Could you update the documentation?

**Comment by JPustkuchen** [comment]
@jfeltkamp should this work in 2.x or is the documentation simply wrong / outdated?

**Comment by jfeltkamp** [comment]
We shouldn't support jQuery documentation. This can all be done in VanillaJS.
