### ISSUE TITLE
Cannot tell if the new content loaded with AJAX should be blocked or not

### ISSUE THREAD

**Issue by kaszarobert** [jfeltkamp/cookiesjsr#14]
Using the cookiesjsrUserConsent event, everything works fine during page load. It blocks what it needs to when not given consent. What can we do with dynamically loaded contents and AJAX updates? How can we determine if the newly loaded content should be blocked or not? Do we have to read from cookies or do we have to create a cookiesjsrUserConsent event manually?

**Comment by sasa-jovanovic-sakiland** [comment]
It seems we need to create event manually. Here's my example with jQuery:

```
// Fire a cookie's event.
let services = $.cookie('cookiesjsr');
if (services) {
  services = JSON.parse(services);
}
else {
  services = {};
}

let options = {services: services};
document.dispatchEvent(new CustomEvent("cookiesjsrUserConsent", {detail: options}));
```

**Comment by JPustkuchen** [comment]
@kaszarobert does https://www.drupal.org/project/klaro solve this? Maybe if not, also create a request over there. I'm not sure if we should ever solve this in COOKiES?

**Comment by JPustkuchen** [comment]
BTW I think this is something this lib can not solve. For Drupal it would be "context" handling. Other frameworks may solve it differently.

**Comment by jfeltkamp** [comment]
The solution of @sasa-jovanovic-sakiland  is exactly what is required. With jQuery you can use ajaxComplete function. I don't know if there is also a solution for vanillaJS.
