### ISSUE TITLE
Can't subscribe to an event precisely when the user chose something

### ISSUE THREAD

**Issue by kaszarobert** [jfeltkamp/cookiesjsr#16]
The problem with cookiesjsrUserConsent event that it is fired also during page load. At then, the user didn't choose anything at all yet. That way we can't write code that does something only when the user given his consent.

Maybe there should be a separate event for these.

**Comment by kaszarobert** [comment]
Well, there's a way right now: using cookiesjsrCallbackResponse but that only works if I need to communicate with servers.

I'm still suggesting that it would be much more intuitive to introduce a cookiesjsrUserConsentChanged event for these occasions.

**Comment by JPustkuchen** [comment]
cookiesjsrUserConsentChanged makes sense to me. @jfeltkamp should decide, if it's still worth it. Does https://www.drupal.org/project/klaro solve this @kaszarobert ?

**Comment by jfeltkamp** [comment]
Do I understand correct @kaszarobert:
You would like to have two (or three) different kinds of events:
When page is loaded: cookiesjsrUserConsent 
When user gave initial consent:  cookiesjsrUserConsent**Init**
When user has changed consent:  cookiesjsrUserConsent**Change**

Can you also describe your use case?

**Comment by jfeltkamp** [comment]
Please re-open if there is interest in a more differentiated event handling.
