### ISSUE TITLE
Use text/plain to block scripts instead of application/json

### ISSUE THREAD

**Issue by JPustkuchen** [jfeltkamp/cookiesjsr#19]
Same as https://www.drupal.org/project/cookies/issues/3303020 but for the cookiesjsr library. See the issue for details.

**Comment by JPustkuchen** [comment]
@jfeltkamp possible improvement for 2.x?

**Comment by jfeltkamp** [comment]
@JPustkuchen I think, nothing to do here. The library just fires the consent event, all the rest is done in drupal custom JS.

Close issue ??

**Comment by JPustkuchen** [comment]
@jfeltkamp yes sorry, super old issue!
