### ISSUE TITLE
Document cookiesjsr-preloader.min.js vs. cookiesjsr.min.js

### ISSUE THREAD

**Issue by JPustkuchen** [jfeltkamp/cookiesjsr#20]
See question in https://www.drupal.org/project/cookies/issues/3301976#comment-14644957

cookiesjsr-preloader.min.js vs. cookiesjsr.min.js is unclear with only the minified source code.

Could you add some documentation in the README.md about the two files and when to use which one, please?

**Comment by vredeling** [comment]
And supply the unminified source please.

**Comment by jfeltkamp** [comment]
The preloader is designed to prevent the library from being loaded when it is not necessary. Since the app has been rewritten in Svelte, the preloader is barely smaller than the library itself. Therefore, the preloader is no longer necessary.
