### ISSUE TITLE
Rename Rename JS "fallback" function to consentGiven() / consentDenied()

### ISSUE THREAD

**Issue by JPustkuchen** [jfeltkamp/cookiesjsr#21]
See drupal issue and discussion: https://www.drupal.org/i/3293376
Commit: https://git.drupalcode.org/project/cookies/-/commit/15cb8ea

The change should be adopted here for:
- Documentation
- Example Code
- Implementation

**Comment by jfeltkamp** [comment]
@JPustkuchen I think, nothing to do here except some changes in the README.md.

Close issue ??

**Comment by JPustkuchen** [comment]
Yup!
