### ISSUE TITLE
Need event when cookies setting button is clicked.

### ISSUE THREAD

**Issue by saurabh-vijayvargiya** [jfeltkamp/cookiesjsr#22]
Hi, thanks for this amazing library.

I am using the Cookies Drupal module which uses this library. I want to edit the look and feel of the consent block. I want to add the title of the banner info. Though I did that using other means, but I want to know when user clicks on customize/cookies setting button.

I have tried to subscribe the click event listener on this button but code does not reach the button. Please suggest a way to know when user clicks on the cookie setting button.

**Comment by jfeltkamp** [comment]
Add a 
`document.addEventListener("click", (event) => { 
  if (event.target.classList.contains('cookiesjsr-settings') {
    // do stuff
  }; 
)};
`
then check if the event target is the button you ment.
