### ISSUE TITLE
Add new option 'cookieDocsTarget' to toogle target="_blank" attribute

### ISSUE THREAD

**Issue by sunlix** [jfeltkamp/cookiesjsr#23]
Hi,

I have added an issue to the Drupal issue queue for adding a new option to toggle the `target="_blank"` attribute on the cookie docs links.

Forcing the user to open a link in a new window is not accessible because all browsers opens the link a forefround and distracts the user from the current context. So best UX is always to let the user decide how they want to navigate throug the internet.

see https://www.drupal.org/project/cookies/issues/3366452

**Comment by vistree** [comment]
I would agree, that the _blank target attribute should be removed from all links. For accessibility reasons, users should decide on there own how to open links (using right mouse context menu)

**Comment by JPustkuchen** [comment]
Or maybe this could be a setting in 2.x @jfeltkamp ?

**Comment by jfeltkamp** [comment]
[2.x 91ae381] #23 Removed target _blank from configuration, imprint, privacy links.

**Comment by JPustkuchen** [comment]
@jfeltkamp we need a setting for each of these links in COOKiES module then, right?

**Comment by JPustkuchen** [comment]
Here we go: https://www.drupal.org/project/cookies/issues/3493869

**Comment by jfeltkamp** [comment]
@JPustkuchen  For now I just remove the target _blanks. I think that such minor blows up the configuration and complexity.  - Do you think it is required? - Then reopen issue. If yes, we should add a single boolean/checkbox 'Open links in a new window/tab' for all links (Imprint, Privacy and Cookie docs). - PS.: There already is a ticket and a MR by sunlix. But we should then change the naming of the checkbox. 
Now the text in the Layer and the Intro text for Groups may contain HTML. Custom links can also be attached here. This could be in alternative.

**Comment by JPustkuchen** [comment]
@jfeltkamp you decide. From a users perspective I think for **external links** it would typically make sense to open them target blank (ux) and add maybe even rel="noopener" (privacy) (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel)

Not sure yet if we should do it 
- per link (most flexible)
- for external links (most typical)
- global setting for all links (most inflexible)

What would you prefer?

**Comment by jfeltkamp** [comment]
@JPustkuchen Yes, correct. I have a good idea.

Let's do this along this best-practice and without configuration:
1. If link is just an **internal path** => no target, no rel
2. If link is **internal** but comes as **full url** with https://... => target="_blank", no rel
(so you have control over the target attribute)
3. If link is **external** => target="_blank", rel="noopener nofollow"

**Comment by JPustkuchen** [comment]
@jfeltkamp indeed super smart idea! Like that. We should then document that as description below the fields in Drupal.

**Comment by jfeltkamp** [comment]
[2.x 281bc20] #23 Link target/rel behavior derived from uri

Realized link target/rel behavior as described above. Will document this in config form in drupal/cookies.

**Comment by jfeltkamp** [comment]
Added documentation to the drupal form and fixed pending issue:
https://www.drupal.org/project/cookies/issues/3493869#comment-15903379
