### ISSUE TITLE
How to set httpOnly flag on cookiesjsr

### ISSUE THREAD

**Issue by WorkisWork** [jfeltkamp/cookiesjsr#24]
I haven't found an option for this. Is this available?

**Comment by JPustkuchen** [comment]
I think this will need a dedicated setting for 2.x @jfeltkamp ?

**Comment by jfeltkamp** [comment]
Why you need httpOnly. 
I think it doesn't make too much sense to set httpOnly property on the cookie, because the cookiejsr cookie is set and used by Javascript.
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

**Comment by JPustkuchen** [comment]
Right! Secure and SameSite are already implemented.
