### ISSUE TITLE
Cookie settings modal buttons are not visible on smaller screens

### ISSUE THREAD

**Issue by sourojeet2001** [jfeltkamp/cookiesjsr#25]
Hi,
I've created a corresponding issue on drupal.org for the same on the Cookies module, but as per my findings it seems like the issue is of the library that the module is dependent upon, hence I think it'll be better to address that issue here as a part of the library itself, so that if the library gets used anywhere else, the solution will mitigate that issue over there also.

For a detailed overview of the issue, please refer to the D.O issue:
https://www.drupal.org/project/cookies/issues/3457021

**Comment by sourojeet2001** [comment]
Hello,
I've prepared the solution, but unfortunately it seems like the repo is maintaining some sort of strict push access and as a result I cannot raise an MR for the same.
Hence as of now I've uploaded a patch on D.O:
https://www.drupal.org/files/issues/2024-07-08/3457021-14.patch
On applying it on the library the issue is getting resolved, for more ref you can check out the D.O issue!
It'll be great if you can grant me push access, then I can convert the patch to a corresponding PR, which will be more effective solution I believe.

**Comment by JPustkuchen** [comment]
@sourojeet2001 please check, if this issue is still present in the 2.x branch.

**Comment by sourojeet2001** [comment]
Yes @JPustkuchen , The issue still persist on the 2.x branch. I uninstalled and reinstalled the cookies module on my D10 instance which should pull all the latest changes as per default branch of 2.x. But I do see the same issue.
Please refer to my latest patch on the D.O issue which addresses your multilingual style breaking concern as well.
Updating the link to the patch here as well: https://www.drupal.org/files/issues/2024-10-04/3457021-20.patch

Also attaching screenshots of the issue persistence on the latest branch for quick ref:
![Screenshot from 2024-12-11 17-45-18](https://github.com/user-attachments/assets/0e31e589-8f93-41a6-ab9e-06242f92b74e)

**Comment by JPustkuchen** [comment]
@sourojeet2001 please re-check that it's 2.0.0-alpha1. Did you use `composer require drupal/cookies:^2 -W`? The -W and ^2 are both important to upgrade

**Comment by jfeltkamp** [comment]
[2.x d258dab] #25 Fixed accept/deny buttons not visible
