### ISSUE TITLE
[2.x] "cookiesjsr-preloader.min.js" contains import statement

### ISSUE THREAD

**Issue by joshsedl** [jfeltkamp/cookiesjsr#26]
"cookiesjsr-preloader.min.js" contains an import statement:
![image](https://github.com/user-attachments/assets/1b9cf959-fe16-43d0-b4ee-c930e850d438)

> Uncaught SyntaxError: Cannot use import statement outside a module (at cookiesjsr-preloader.min.js:12:1)

**Comment by joshsedl** [comment]
Update: This is a general problem for the 2.0.0. The "2.x-dev" release on packagist is also affected for some reason.

**Comment by jfeltkamp** [comment]
It is in Progress. Sorry, Need some more time to finish the 2.x Version

**Comment by jfeltkamp** [comment]
Preloader is not needed anymore. Since library built in Svelte, the library is small enough to be present all the time.
