### ISSUE TITLE
Privacy Policy, Imprint and Cookie documentation links should NOT be shown, when URI is empty

### ISSUE THREAD

**Issue by joshsedl** [jfeltkamp/cookiesjsr#32]
When setting up the COOKiES module, the "Imprint" and "Privacy policy" URIs are 
not initialized:
![image](https://github.com/user-attachments/assets/cd796491-7b3e-41f3-af6c-559e40a3e4cd)

The old version would hide these links, if no URI is set:
![image](https://github.com/user-attachments/assets/efe7364e-10a1-4d24-81b1-fd264138c584)

But the new version sets them with an empty "href" attribute:
![image](https://github.com/user-attachments/assets/0db10772-f417-490a-9dfc-b4e31a278b44)

**Comment by jfeltkamp** [comment]
[2.x b6de785] #32 Conditional display of privacy and imprint links
