### ISSUE TITLE
Pressing on "Cookie Settings" won't automatically select the first service tab

### ISSUE THREAD

**Issue by joshsedl** [jfeltkamp/cookiesjsr#33]
When pressing on "Cookie Settings" on the old banner, the "Cookie Settings" dialog would open with the first service entity preselected:
![image](https://github.com/user-attachments/assets/43bda441-0b3c-43f0-a422-b261270f7bac)

Now in 2.x, pressing "Cookie Settings" will open the dialog, but the first service entity is NOT selected:
![image](https://github.com/user-attachments/assets/9b8c328d-095f-48fd-a90d-49da113141dc)

In this case, pressing "Functional" will lead to the old correct view:
![image](https://github.com/user-attachments/assets/63a262db-0423-4231-96bb-cff8ca6050d9)

**Comment by jfeltkamp** [comment]
[2.x da89c02] #33 Active tab not set on layer open
