### ISSUE TITLE
Contains console.log's

### ISSUE THREAD

**Issue by JPustkuchen** [jfeltkamp/cookiesjsr#37]
Cookie actions are logged to the console. I think that shouldn't be the case in production or be behind a "debug" option in the settings?

```
Y.subscribe(n => {
    console.log("services update: ", n)
}
```

**Comment by jfeltkamp** [comment]
Hey @JPustkuchen,
definitly fixed. See duplicate #34 and make sure you are using the latest release. 
Open cookiesjsr.min.js in browser network tab and check, if version number is >= 2.0.2 

`
/** @license CookiesJSR 2.0.2
`

**Comment by JPustkuchen** [comment]
Thanks @jfeltkamp strange, perhaps indeed there was an old version in cache. Sorry for the trouble then. -.-
