### ISSUE TITLE
Cookie setting checkbox title attribute always denied

### ISSUE THREAD

**Issue by kirkkala** [jfeltkamp/cookiesjsr#4]
Once again first thank you for maintaining this helpful package!

But one minor detail noticed and hard to fix with just minified javascript. Please see screenshot, no matter in which state the checkbox (toggle button) is the element title is always "denied".
<img width="1128" alt="cookiesjsr-setting always-denied" src="https://user-images.githubusercontent.com/5946065/112985912-7fffdb80-9169-11eb-8aa6-2719bf65596b.png">

**Comment by JPustkuchen** [comment]
@jfeltkamp did you recognize this issue?

**Comment by jfeltkamp** [comment]
This must be a translation issue. Please check your config files for something like:
`
  "allowed": "denied",
  "denied": "denied",
`

**Comment by JPustkuchen** [comment]
@kirkkala any feedback? Or can this be closed?

**Comment by jfeltkamp** [comment]
Seems not to be an issue anymore.
