### ISSUE TITLE
Provide as npm package

### ISSUE THREAD

**Issue by JPustkuchen** [jfeltkamp/cookiesjsr#5]
Hi Joachim,

it would be cool to have this as npm package. Besides general benefits it would also be helpful to simply download the library with composer through asset-packagist:
`composer require npm-asset/cookiesjsr`

Name should be equal so that it's automatically downloaded into the correct library subfolder in Drupal.

What do you think?

> The alternative (if you uncheck) is to download the library and place it in the library folder, so library file can be reached e.g. under path: {docroot}/libraries/cookiesjsr/dist/cookiesjsr.min.js.

**Comment by JPustkuchen** [comment]
Also see https://docs.github.com/en/actions/guides/publishing-nodejs-packages for automation :)

**Comment by JPustkuchen** [comment]
Just saw this has a composer package, which is absolutely enough for the case above. But would still be helpful for non-php cases?

https://docs.npmjs.com/creating-and-publishing-unscoped-public-packages

`npm publish`

**Comment by JPustkuchen** [comment]
@jfeltkamp I think pushing this to nom would still make sense for 2.x? Maybe this can also be automated here at GitHub?

**Comment by JPustkuchen** [comment]
Here's the composer alternative:
`composer require jfeltkamp/cookiesjsr:^2`

So this is already fine, maybe we should add that to the documentation?

**Comment by joshsedl** [comment]
I'd see this as minor, as this would only apply for non php use cases. For php use cases, `composer require jfeltkamp/cookiesjsr:^2` is already enough.
