### ISSUE TITLE
Document how to change preferences (re-open consent banner)

### ISSUE THREAD

**Issue by JPustkuchen** [jfeltkamp/cookiesjsr#7]
Hi @jfeltkamp,

perhaps I'm blind, but I can't find any documentation how to manually show the Cookie banner again to change preferences. Could you perhaps add a JS snippet for that to the documentation?

Thank you!

**Comment by jfeltkamp** [comment]
You just need a link with with the opening hash configured with 'interface.openSettingsHash' (default: "#editCookieSettings").
`<a href="#editCookieSettings">Cookie settings</a>`
